[tox]
minversion = 4.4.3
envlist = py{39,310,311,312}, lint, coverage
isolated_build = True

[testenv]
package = wheel
wheel_build_env = .pkg
parallel_show_output = True
extras =
  test
commands =
  pytest {posargs}

[testenv:style]
extras =
  style
commands =
  ruff format src/ test/
  ruff check --fix src/ test/

[testenv:lint]
basepython = python3.11
extras =
  lint
commands =
  ruff format --check src/ test/
  ruff check src/ test/
  mypy src/

[testenv:coverage]
basepython = python3.11
extras =
  test
commands =
  pytest --cov=src/qeco/
